const myUsersQueryExplained: string = `
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; ---> IF I DO NOT SPECIFY A userId WHEN USER SIGNS IN FOR FIRST TIME,
THIS WILL SIGNAL SUPABASE TO CREATE ONE FOR ME USING uuid_generate_v4()

CREATE TABLE allUsers (
  userId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  googleId TEXT UNIQUE,
  username TEXT,
  balance DECIMAL(10,2) DEFAULT 0,
  creditors_total DECIMAL (10,2) DEFAULT 0,
  debtors_total DECIMAL(10,2) DEFAULT 0,
  allOfferedByMeId TEXT, -- WILL BE AN ID STRING THAT ALL LOANS I'VE CREATED WILL SHARE
  allOfferedToMeId TEXT, --WILL BE AN ID THAT ALL LOANS OFFERED TO ME WILL SHARE
  allApplicationsId TEXT, --WILL BE AN ID THAT ALL APPLICATIONS BY USER WILL SHARE 
  creditScore INT DEFAULT 0, --WILL BE A ROUNDED FLOOR VALUE  
  loan_count INT DEFAULT 0, -- HOW MANY LOANS I HAVE SUCCESSFULLY GIVEN OUT 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp
);
`;
