import type { Metadata } from "next";
import "./globals.css";
import { Taviraj } from "next/font/google";
import { SideBar } from "@/components/forLayout";

const tav = Taviraj({ subsets: ["latin"], weight: ["200"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tav.className}>
        <div className=" flex flex-col lg:flex-row">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
